In [208]:
import pandas as pd

In [209]:
#Import and cleaning of data from Welcome To The Jungle scraping

dfW = pd.read_csv('/content/drive/MyDrive/Jedha_Fullstack/DataMatch_Project/Data_Cleaning/Dataset_960Offres_WTTJ_Uncleaned.csv')
dfW

,job_title,Field1,Field2,job_type,Field4,job_location,Field6,job_company,Field8,company_description,job_description,Field11
0,Tools & Accounts Administrator,√âducation :\nBac +2,T√©l√©travail partiel possible,CDI\n,Exp√©rience :\n> 3 ans,M√¢con‚Ä¶Voir plus2,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Descriptif du poste\n\nAu sein du d√©partement ...,Profil recherch√©\n\nDipl√¥m√©.e d‚Äôun bac+2 en li...
1,Team Lead - Data Engineering & Analytics Engi...,√âducation :\nNon sp√©cifi√©,T√©l√©travail partiel possible,CDI\n,Exp√©rience :\nNon sp√©cifi√©,"16 Rue du Mail, Paris, 75002",Entre 250 et 2000 salari√©s,Welcome to the Jungle,"M√©dia, Recrutement","Chez Welcome to the Jungle, nous travaillons p...",Descriptif du poste\n\nThe Data team at Welcom...,"Profil recherch√©\n\nAt Welcome to the Jungle, ..."
2,DevSecOps Engineer (SI),√âducation :\nNon sp√©cifi√©,T√©l√©travail partiel possible,CDI\n,Exp√©rience :\nNon sp√©cifi√©,M√¢con‚Ä¶Voir plus3,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Descriptif du poste\n\nAu sein du d√©partement ...,Profil recherch√©\n\nTu as d√©j√† au moins 3 ans ...
3,Data Analyst - Data Engineer (H/F),T√©l√©travail partiel possible,D√©but :\n1 septembre 2023,CDI\n,√âducation :\nBac +5 / Master,"21 Rue Berg√®re, Paris, 75009",Entre 50 et 250 salari√©s,Runview,Audit,"Runview, c‚Äôest le monde de l‚Äôaudit digitalis√©,...",Descriptif du poste\n\nNous recherchons un(e) ...,Profil recherch√©\n\nVous √™tes issu(e) d‚Äôune fo...
4,[Luxe - Retail] Consultant Senior Data & Anal...,Exp√©rience :\n> 5 ans,√âducation :\nBac +5 / Master,CDI\n,NaN,"18 Rue de Tilsitt, Paris, 75017",Entre 250 et 2000 salari√©s,Adone Conseil,"IT / Digital, Transformation",Si vous recherchez un cabinet √† taille humaine...,Descriptif du poste\n\nNous recherchons un Con...,Profil recherch√©\n\nü¶∏ Votre profil :\n\nVous √™...
...,...,...,...,...,...,...,...,...,...,...,...,...
954,Ing√©nieur Big Data - Retail - Bordeaux,Exp√©rience :\n< 6 mois,√âducation :\nBac +5 / Master,CDI\n,NaN,"avenue de Pythagore, Bordeaux, 33700",> 2000 salari√©s,Sopra Steria,"IT / Digital, Organisation / Management","Sopra Steria, l'un des leaders europ√©ens de la...",Descriptif du poste\n\nVotre futur environneme...,Profil recherch√©\n\nVotre profil\n\nDe formati...
955,Data Wrangler,√âducation :\nBac +4,D√©but :\n15 septembre 2023,Stage\n¬†\n(6 mois),Exp√©rience :\n< 6 mois,"la defense, Puteaux",> 2000 salari√©s,Soci√©t√© G√©n√©rale,"Banque, FinTech / InsurTech, Finance","Chez Soci√©t√© G√©n√©rale, nous sommes convaincus ...",Descriptif du poste\n\nLe m√©tier Data Wrangler...,Profil recherch√©\nVous √™tes √©tudiant(e) de for...
956,ALTERNANCE - Data Analyst (F/H),Exp√©rience :\n< 6 mois,√âducation :\nBac +4,Alternance\n,NaN,"18, Rue Barb√®s, Montrouge, 92120",Entre 250 et 2000 salari√©s,Groupe Bayard,"Edition, M√©dia, Presse √©crite","Acteur majeur dans le secteur des m√©dias, Baya...",Descriptif du poste\n\nAu sein de l‚Äô√©quipe Dat...,Profil recherch√©\n\nEn formation sup√©rieure (b...
957,Alternance - Digital & Data Market Analyst - ...,Exp√©rience :\nNon sp√©cifi√©,√âducation :\nNon sp√©cifi√©,Alternance\n,NaN,Serris,> 2000 salari√©s,Henkel,"Grande distribution, Cosm√©tique, E-commerce","En 1876, Fritz Henkel n‚Äôaurait jamais imagin√© ...","Descriptif du poste\n\nChez Henkel, vous pouve...",NaN
958,ASSISTANT.E PRODUCT DATA MANAGER,√âducation :\nBac +4,T√©l√©travail partiel possible,CDD / Temporaire\n,Exp√©rience :\n> 1 an,"Paris 17, 75017",> 2000 salari√©s,Groupe Clarins,Cosm√©tique,Pr√™t √† insuffler de la passion √† votre carri√®r...,Descriptif du poste\n\nLe poste¬†:\n\n¬†\n\nA la...,Profil recherch√©\n\nDescription du profil :\n\...

In [210]:
dfW = dfW.drop_duplicates(subset=["job_description"])
dfW = dfW.rename(columns={"Field11":"profile", "Field6":"company_size", "Field8":"industry"})
dfW = dfW.drop(["Field1", "Field2", "Field4"], axis=1)
for col in dfW.columns:
    dfW[col] = dfW[col].str.replace('\n', ' ')
dfW

,job_title,job_type,job_location,company_size,job_company,industry,company_description,job_description,profile
0,Tools & Accounts Administrator,CDI,M√¢con‚Ä¶Voir plus2,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Descriptif du poste Au sein du d√©partement SI...,Profil recherch√© Dipl√¥m√©.e d‚Äôun bac+2 en lien...
1,Team Lead - Data Engineering & Analytics Engi...,CDI,"16 Rue du Mail, Paris, 75002",Entre 250 et 2000 salari√©s,Welcome to the Jungle,"M√©dia, Recrutement","Chez Welcome to the Jungle, nous travaillons p...",Descriptif du poste The Data team at Welcome ...,"Profil recherch√© At Welcome to the Jungle, we..."
2,DevSecOps Engineer (SI),CDI,M√¢con‚Ä¶Voir plus3,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Descriptif du poste Au sein du d√©partement DS...,Profil recherch√© Tu as d√©j√† au moins 3 ans d‚Äô...
3,Data Analyst - Data Engineer (H/F),CDI,"21 Rue Berg√®re, Paris, 75009",Entre 50 et 250 salari√©s,Runview,Audit,"Runview, c‚Äôest le monde de l‚Äôaudit digitalis√©,...",Descriptif du poste Nous recherchons un(e) Da...,Profil recherch√© Vous √™tes issu(e) d‚Äôune form...
4,[Luxe - Retail] Consultant Senior Data & Anal...,CDI,"18 Rue de Tilsitt, Paris, 75017",Entre 250 et 2000 salari√©s,Adone Conseil,"IT / Digital, Transformation",Si vous recherchez un cabinet √† taille humaine...,Descriptif du poste Nous recherchons un Consu...,Profil recherch√© ü¶∏ Votre profil : Vous √™tes ...
...,...,...,...,...,...,...,...,...,...
954,Ing√©nieur Big Data - Retail - Bordeaux,CDI,"avenue de Pythagore, Bordeaux, 33700",> 2000 salari√©s,Sopra Steria,"IT / Digital, Organisation / Management","Sopra Steria, l'un des leaders europ√©ens de la...",Descriptif du poste Votre futur environnement...,Profil recherch√© Votre profil De formation B...
955,Data Wrangler,Stage ¬† (6 mois),"la defense, Puteaux",> 2000 salari√©s,Soci√©t√© G√©n√©rale,"Banque, FinTech / InsurTech, Finance","Chez Soci√©t√© G√©n√©rale, nous sommes convaincus ...",Descriptif du poste Le m√©tier Data Wrangler e...,Profil recherch√© Vous √™tes √©tudiant(e) de form...
956,ALTERNANCE - Data Analyst (F/H),Alternance,"18, Rue Barb√®s, Montrouge, 92120",Entre 250 et 2000 salari√©s,Groupe Bayard,"Edition, M√©dia, Presse √©crite","Acteur majeur dans le secteur des m√©dias, Baya...",Descriptif du poste Au sein de l‚Äô√©quipe Data ...,Profil recherch√© En formation sup√©rieure (bac...
957,Alternance - Digital & Data Market Analyst - ...,Alternance,Serris,> 2000 salari√©s,Henkel,"Grande distribution, Cosm√©tique, E-commerce","En 1876, Fritz Henkel n‚Äôaurait jamais imagin√© ...","Descriptif du poste Chez Henkel, vous pouvez ...",NaN
958,ASSISTANT.E PRODUCT DATA MANAGER,CDD / Temporaire,"Paris 17, 75017",> 2000 salari√©s,Groupe Clarins,Cosm√©tique,Pr√™t √† insuffler de la passion √† votre carri√®r...,Descriptif du poste Le poste¬†: ¬† A la crois...,Profil recherch√© Description du profil : V...

In [211]:
#Import and cleaning of data from LinkedIn scraping

dfL = pd.read_csv('/content/drive/MyDrive/Jedha_Fullstack/DataMatch_Project/Data_Cleaning/LinkedIn_jobs.csv')
dfL

,Job_title,Job_link,Company,Job_location,Job_description,Seniority_level,Employment_type,Job_function,Industries
0,Data Entry Operator (Remote),https://wf.linkedin.com/jobs/view/data-entry-o...,\n eStaffing Inc.\n,\n Wallis et Futuna\n,Job Tittle- Data Entry Operator (Remote)\n\nJo...,\n Premier emploi\n,\n Temps plein\n,\n Administration\n,\n Recrutement\n
1,Data Entry Clerk - Remote,https://fr.linkedin.com/jobs/view/data-entry-c...,\n eStaffing Inc.\n,\n France\n,Job Tittle- Data Entry Celrk -Remote\n\nJob lo...,\n Premier emploi\n,\n Temps plein\n,\n Administration\n,\n Recrutement\n
2,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,\n E.Leclerc\n,\n Ivry-sur-Seine\n,Description\n\nL COMMERCE est compos√© de 100 c...,\n Premier emploi\n,\n Temps plein\n,\n Technologies de l‚Äôinformation\n ...,\n Commerce de d√©tail de produits d‚Äô√©...
3,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,\n E.Leclerc\n,\n Toulouse\n,"Description\n\nLeader du drive en France, le g...",\n Premier emploi\n,\n Temps plein\n,\n Technologies de l‚Äôinformation\n ...,\n Commerce de d√©tail de produits d‚Äô√©...
4,Data Analyst,https://fr.linkedin.com/jobs/view/data-analyst...,\n Mirakl\n,\n Paris\n,Le secteur des marketplaces cro√Æt deux fois pl...,\n Premier emploi\n,\n Temps plein\n,\n Technologies de l‚Äôinformation\n ...,"\n Technologie, information et Intern..."
...,...,...,...,...,...,...,...,...,...
926,Stage - bras droit co-fondateur - data & opera...,https://fr.linkedin.com/jobs/view/stage-bras-d...,\n Climb\n,\n Paris\n,L'entreprise :\n\n\n\n\nNotre mission : Permet...,\n Non pertinent\n,\n Temps plein\n,\n D√©veloppement commercial et Vent...,"\n Transport, Logistique, Supply Chai..."
927,Consultant Strat√©gie Cloud - H/F,https://fr.linkedin.com/jobs/view/consultant-s...,\n Thales\n,\n Lyon\n,QUI ETES-VOUS ?\n\n\n\n\nDipl√¥m√© d‚Äôune grande ...,\n Non pertinent\n,\n Temps plein\n,\n Autre\n,\n Fabrication pour l‚Äôindustrie de la...
928,Analytics Architect,https://fr.linkedin.com/jobs/view/analytics-ar...,\n IGT Solutions\n,\n Paris et p√©riph√©rie\n,Role - Data Scientist\n\nSkillsets - Technical...,\n Manager\n,\n Temps plein\n,\n Ing√©nierie et Technologies de l‚Äô...,\n Services et conseil informatiques\...
929,Accountant Fintech,https://fr.linkedin.com/jobs/view/accountant-f...,\n Mobilize Pay\n,"\n √éle-de-France, France\n ...","About us\n\n\n\n\nAt MOBILIZE PAY, we‚Äôre on a ...",\n Manager\n,\n Temps plein\n,\n Comptabilit√©/audit\n,\n Services financiers\n
930,Stage Business Analyst Parfums H/F,https://fr.linkedin.com/jobs/view/stage-busine...,\n Cartier\n,\n Paris\n,Cartier France recherche un(e) stagiaire : Bus...,\n Stagiaire / Alternant\n,\n Stage / Alternance\n,"\n Publicit√©, Marketing et Responsa...",\n Commerce de d√©tail d‚Äôarticles de l...

In [212]:
dfL = dfL.drop_duplicates(subset=["Job_description"])
dfL

,Job_title,Job_link,Company,Job_location,Job_description,Seniority_level,Employment_type,Job_function,Industries
0,Data Entry Operator (Remote),https://wf.linkedin.com/jobs/view/data-entry-o...,\n eStaffing Inc.\n,\n Wallis et Futuna\n,Job Tittle- Data Entry Operator (Remote)\n\nJo...,\n Premier emploi\n,\n Temps plein\n,\n Administration\n,\n Recrutement\n
1,Data Entry Clerk - Remote,https://fr.linkedin.com/jobs/view/data-entry-c...,\n eStaffing Inc.\n,\n France\n,Job Tittle- Data Entry Celrk -Remote\n\nJob lo...,\n Premier emploi\n,\n Temps plein\n,\n Administration\n,\n Recrutement\n
2,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,\n E.Leclerc\n,\n Ivry-sur-Seine\n,Description\n\nL COMMERCE est compos√© de 100 c...,\n Premier emploi\n,\n Temps plein\n,\n Technologies de l‚Äôinformation\n ...,\n Commerce de d√©tail de produits d‚Äô√©...
3,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,\n E.Leclerc\n,\n Toulouse\n,"Description\n\nLeader du drive en France, le g...",\n Premier emploi\n,\n Temps plein\n,\n Technologies de l‚Äôinformation\n ...,\n Commerce de d√©tail de produits d‚Äô√©...
4,Data Analyst,https://fr.linkedin.com/jobs/view/data-analyst...,\n Mirakl\n,\n Paris\n,Le secteur des marketplaces cro√Æt deux fois pl...,\n Premier emploi\n,\n Temps plein\n,\n Technologies de l‚Äôinformation\n ...,"\n Technologie, information et Intern..."
...,...,...,...,...,...,...,...,...,...
926,Stage - bras droit co-fondateur - data & opera...,https://fr.linkedin.com/jobs/view/stage-bras-d...,\n Climb\n,\n Paris\n,L'entreprise :\n\n\n\n\nNotre mission : Permet...,\n Non pertinent\n,\n Temps plein\n,\n D√©veloppement commercial et Vent...,"\n Transport, Logistique, Supply Chai..."
927,Consultant Strat√©gie Cloud - H/F,https://fr.linkedin.com/jobs/view/consultant-s...,\n Thales\n,\n Lyon\n,QUI ETES-VOUS ?\n\n\n\n\nDipl√¥m√© d‚Äôune grande ...,\n Non pertinent\n,\n Temps plein\n,\n Autre\n,\n Fabrication pour l‚Äôindustrie de la...
928,Analytics Architect,https://fr.linkedin.com/jobs/view/analytics-ar...,\n IGT Solutions\n,\n Paris et p√©riph√©rie\n,Role - Data Scientist\n\nSkillsets - Technical...,\n Manager\n,\n Temps plein\n,\n Ing√©nierie et Technologies de l‚Äô...,\n Services et conseil informatiques\...
929,Accountant Fintech,https://fr.linkedin.com/jobs/view/accountant-f...,\n Mobilize Pay\n,"\n √éle-de-France, France\n ...","About us\n\n\n\n\nAt MOBILIZE PAY, we‚Äôre on a ...",\n Manager\n,\n Temps plein\n,\n Comptabilit√©/audit\n,\n Services financiers\n
930,Stage Business Analyst Parfums H/F,https://fr.linkedin.com/jobs/view/stage-busine...,\n Cartier\n,\n Paris\n,Cartier France recherche un(e) stagiaire : Bus...,\n Stagiaire / Alternant\n,\n Stage / Alternance\n,"\n Publicit√©, Marketing et Responsa...",\n Commerce de d√©tail d‚Äôarticles de l...

In [213]:
dfL = dfL.rename(columns={"Job_description" : "job_description", "Job_title":"job_title", "Company":"job_company", "Job_location":"job_location", "Job_link":"job_link"})
dfL = dfL.drop(["Job_function", "Industries"], axis=1)
for col in dfL.columns:
    dfL[col] = dfL[col].str.replace('\n', ' ')
dfL

,job_title,job_link,job_company,job_location,job_description,Seniority_level,Employment_type
0,Data Entry Operator (Remote),https://wf.linkedin.com/jobs/view/data-entry-o...,eStaffing Inc.,Wallis et Futuna,Job Tittle- Data Entry Operator (Remote) Job ...,Premier emploi,Temps plein
1,Data Entry Clerk - Remote,https://fr.linkedin.com/jobs/view/data-entry-c...,eStaffing Inc.,France,Job Tittle- Data Entry Celrk -Remote Job loca...,Premier emploi,Temps plein
2,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,E.Leclerc,Ivry-sur-Seine,Description L COMMERCE est compos√© de 100 col...,Premier emploi,Temps plein
3,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,E.Leclerc,Toulouse,"Description Leader du drive en France, le gro...",Premier emploi,Temps plein
4,Data Analyst,https://fr.linkedin.com/jobs/view/data-analyst...,Mirakl,Paris,Le secteur des marketplaces cro√Æt deux fois pl...,Premier emploi,Temps plein
...,...,...,...,...,...,...,...
926,Stage - bras droit co-fondateur - data & opera...,https://fr.linkedin.com/jobs/view/stage-bras-d...,Climb,Paris,L'entreprise : Notre mission : Permettre √†...,Non pertinent,Temps plein
927,Consultant Strat√©gie Cloud - H/F,https://fr.linkedin.com/jobs/view/consultant-s...,Thales,Lyon,QUI ETES-VOUS ? Dipl√¥m√© d‚Äôune grande √©cole...,Non pertinent,Temps plein
928,Analytics Architect,https://fr.linkedin.com/jobs/view/analytics-ar...,IGT Solutions,Paris et p√©riph√©rie,Role - Data Scientist Skillsets - Technical s...,Manager,Temps plein
929,Accountant Fintech,https://fr.linkedin.com/jobs/view/accountant-f...,Mobilize Pay,"√éle-de-France, France","About us At MOBILIZE PAY, we‚Äôre on a missi...",Manager,Temps plein
930,Stage Business Analyst Parfums H/F,https://fr.linkedin.com/jobs/view/stage-busine...,Cartier,Paris,Cartier France recherche un(e) stagiaire : Bus...,Stagiaire / Alternant,Stage / Alternance

In [214]:
#Import and cleaning of data from Indeed scraping

dfI = pd.read_csv('/content/drive/MyDrive/Jedha_Fullstack/DataMatch_Project/Data_Cleaning/Indeed_Data_France_Pauline.csv', error_bad_lines=False)
dfI

<ipython-input-214-5cd2f6054a8c>:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  dfI = pd.read_csv('/content/drive/MyDrive/Jedha_Fullstack/DataMatch_Project/Data_Cleaning/Indeed_Data_France_Pauline.csv', error_bad_lines=False)

,job_title,job_company,job_location,job_type,job_description,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Responsable Data engineer,arm√©e de l'Air et de l'Espace,33000 Bordeaux,D√©tails du poste\nAucune correspondance avec v...,Vous √™tes charg√©(e) :- De piloter et r√©aliser ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DATA ENGINEER (H/F),EOSIS,13790 Rousset,D√©tails du poste\nAucune correspondance avec v...,Vous souhaitez rejoindre un groupe dynamique e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Analyste d√©veloppeur - data scientist (H/F),EURO-INFORMATION DEVELOPPEMENTS,67000 Strasbourg,D√©tails du poste\nAucune correspondance avec v...,"Qui sommes nous\nEuro-Information, filiale tec...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alternance - Data Steward H/F,Groupe GEMA,Montpellier (34),D√©tails du poste\nAucune correspondance avec v...,"L‚ÄôIA School, l‚ÄôEcole de l‚ÄôIntelligence Artific...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Consultant Senior Data Gouvernance (F/H),Novencia,Paris (75),no type description,Carnet de route\nNovencia accompagne ses clien...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410,DATA MANAGER RECHERCHE CLINIQUE (H/F) (Nouvell...,POLE DIRECTION,Bron (69),D√©tails du poste\nAucune correspondance avec v...,Quotit√© de temps % : 100\nPoste jour / nuit : ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1411,DATA SCIENTIST SCORE ET MODELISATION (F/H),BPCE Compagnie Europeenne de Garanties et Caut...,Paris (75),D√©tails du poste\nAucune correspondance avec v...,Description de l'entreprise\nLa Compagnie Euro...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1412,Administrateur base de donn√©es (IT) / Freelance,Gentis Recruitment SAS,Paris (75),D√©tails du poste\nAucune correspondance avec v...,La mission\n\nL‚Äôadministration des serveurs de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1413,Administrateur base de donn√©es (IT) / Freelance,Gentis Recruitment SAS,Paris (75),D√©tails du poste\nAucune correspondance avec v...,La mission\n\nL‚Äôadministration des serveurs de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1414,Administrateur base de donn√©es (IT) / Freelance,Gentis Recruitment SAS,Paris (75),D√©tails du poste\nAucune correspondance avec v...,La mission\n\nL‚Äôadministration des serveurs de...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [215]:
dfI = dfI.iloc[:,:5]
dfI = dfI.drop("job_type", axis=1)
dfI

,job_title,job_company,job_location,job_description
0,Responsable Data engineer,arm√©e de l'Air et de l'Espace,33000 Bordeaux,Vous √™tes charg√©(e) :- De piloter et r√©aliser ...
1,DATA ENGINEER (H/F),EOSIS,13790 Rousset,Vous souhaitez rejoindre un groupe dynamique e...
2,Analyste d√©veloppeur - data scientist (H/F),EURO-INFORMATION DEVELOPPEMENTS,67000 Strasbourg,"Qui sommes nous\nEuro-Information, filiale tec..."
3,Alternance - Data Steward H/F,Groupe GEMA,Montpellier (34),"L‚ÄôIA School, l‚ÄôEcole de l‚ÄôIntelligence Artific..."
4,Consultant Senior Data Gouvernance (F/H),Novencia,Paris (75),Carnet de route\nNovencia accompagne ses clien...
...,...,...,...,...
1410,DATA MANAGER RECHERCHE CLINIQUE (H/F) (Nouvell...,POLE DIRECTION,Bron (69),Quotit√© de temps % : 100\nPoste jour / nuit : ...
1411,DATA SCIENTIST SCORE ET MODELISATION (F/H),BPCE Compagnie Europeenne de Garanties et Caut...,Paris (75),Description de l'entreprise\nLa Compagnie Euro...
1412,Administrateur base de donn√©es (IT) / Freelance,Gentis Recruitment SAS,Paris (75),La mission\n\nL‚Äôadministration des serveurs de...
1413,Administrateur base de donn√©es (IT) / Freelance,Gentis Recruitment SAS,Paris (75),La mission\n\nL‚Äôadministration des serveurs de...
1414,Administrateur base de donn√©es (IT) / Freelance,Gentis Recruitment SAS,Paris (75),La mission\n\nL‚Äôadministration des serveurs de...

In [216]:
dfI = dfI.drop_duplicates(subset=["job_description"])
for col in dfI.columns:
    dfI[col] = dfI[col].str.replace('\n', ' ')
dfI

<ipython-input-216-8a83c3c4075a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfI[col] = dfI[col].str.replace('\n', ' ')

,job_title,job_company,job_location,job_description
0,Responsable Data engineer,arm√©e de l'Air et de l'Espace,33000 Bordeaux,Vous √™tes charg√©(e) :- De piloter et r√©aliser ...
1,DATA ENGINEER (H/F),EOSIS,13790 Rousset,Vous souhaitez rejoindre un groupe dynamique e...
2,Analyste d√©veloppeur - data scientist (H/F),EURO-INFORMATION DEVELOPPEMENTS,67000 Strasbourg,"Qui sommes nous Euro-Information, filiale tech..."
3,Alternance - Data Steward H/F,Groupe GEMA,Montpellier (34),"L‚ÄôIA School, l‚ÄôEcole de l‚ÄôIntelligence Artific..."
4,Consultant Senior Data Gouvernance (F/H),Novencia,Paris (75),Carnet de route Novencia accompagne ses client...
...,...,...,...,...
1407,Data Engineer H/F,Dexton consulting,75002 Paris,Vous souhaitez int√©grer un groupe √† taille hum...
1408,INTERNSHIP OFFER - RESEARCH INTERNATIONAL PROJ...,SNCF,Saint-Denis (93),Vos missions The aim of this internship is to ...
1409,Analyste Quantitatif - Data Scientist (F/H),Ofi Invest Asset Management,Paris (75),A propos d'Ofi Invest : Ofi Invest est aujourd...
1410,DATA MANAGER RECHERCHE CLINIQUE (H/F) (Nouvell...,POLE DIRECTION,Bron (69),Quotit√© de temps % : 100 Poste jour / nuit : J...
1411,DATA SCIENTIST SCORE ET MODELISATION (F/H),BPCE Compagnie Europeenne de Garanties et Caut...,Paris (75),Description de l'entreprise La Compagnie Europ...

In [217]:
dfW.head(3)

,job_title,job_type,job_location,company_size,job_company,industry,company_description,job_description,profile
0,Tools & Accounts Administrator,CDI,M√¢con‚Ä¶Voir plus2,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Descriptif du poste Au sein du d√©partement SI...,Profil recherch√© Dipl√¥m√©.e d‚Äôun bac+2 en lien...
1,Team Lead - Data Engineering & Analytics Engi...,CDI,"16 Rue du Mail, Paris, 75002",Entre 250 et 2000 salari√©s,Welcome to the Jungle,"M√©dia, Recrutement","Chez Welcome to the Jungle, nous travaillons p...",Descriptif du poste The Data team at Welcome ...,"Profil recherch√© At Welcome to the Jungle, we..."
2,DevSecOps Engineer (SI),CDI,M√¢con‚Ä¶Voir plus3,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Descriptif du poste Au sein du d√©partement DS...,Profil recherch√© Tu as d√©j√† au moins 3 ans d‚Äô...

In [218]:
dfL.head(3)

,job_title,job_link,job_company,job_location,job_description,Seniority_level,Employment_type
0,Data Entry Operator (Remote),https://wf.linkedin.com/jobs/view/data-entry-o...,eStaffing Inc.,Wallis et Futuna,Job Tittle- Data Entry Operator (Remote) Job ...,Premier emploi,Temps plein
1,Data Entry Clerk - Remote,https://fr.linkedin.com/jobs/view/data-entry-c...,eStaffing Inc.,France,Job Tittle- Data Entry Celrk -Remote Job loca...,Premier emploi,Temps plein
2,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,E.Leclerc,Ivry-sur-Seine,Description L COMMERCE est compos√© de 100 col...,Premier emploi,Temps plein

In [219]:
dfI.head(3)

,job_title,job_company,job_location,job_description
0,Responsable Data engineer,arm√©e de l'Air et de l'Espace,33000 Bordeaux,Vous √™tes charg√©(e) :- De piloter et r√©aliser ...
1,DATA ENGINEER (H/F),EOSIS,13790 Rousset,Vous souhaitez rejoindre un groupe dynamique e...
2,Analyste d√©veloppeur - data scientist (H/F),EURO-INFORMATION DEVELOPPEMENTS,67000 Strasbourg,"Qui sommes nous Euro-Information, filiale tech..."

In [220]:
dfW["job_description"] = dfW["job_description"].apply(lambda x : str(x).split("poste  ", 1)[-1])

In [221]:
dfW["job_description"][2]

'Au sein du d√©partement DSI et en interaction avec les √©quipes developement, DevOps, Deployment Project, Customer Satisfaction‚Ä¶, ton r√¥le sera d‚Äôorchestrer et de r√©soudre des probl√©matiques de s√©curit√© aussi bien li√©es √† l‚Äôinfrastructure qu‚Äôaux produits d√©velopp√©s par le groupe.  Plus en d√©tails, tes missions seront :  S√©curisation des infrastructures internes et externes : accompagner l‚Äôensemble de la DSI et des √©quipes de d√©veloppement aussi bien dans la rem√©diation des vuln√©rabilit√©s internes et externes que dans l‚Äôint√©gration de la s√©curit√© √† tous les stades du d√©veloppement et des projets SI. De m√™me, mettre en place les proc√©dures, automatiser les contr√¥les et int√©grer des nouveaux outils n√©cessaires au maintien de la s√©curit√©. Supervision de la s√©curit√©: surveiller les alertes, participer √† la gestion et √† la r√©solution technique des incidents de s√©curit√© et √©galement √† la cr√©ation de nouvelles r√®gles de d√©tection du SIEM Splunk en partenariat avec notre SOC mutualis√©. Accompagnement des √©quipes : assister les √©quipes au quotidien dans leurs besoins et questions relatives √† la s√©curisation des infrastructures et environnements de test, preprod et production et participer au support N2/N3 des tickets en lien avec l‚Äôinfrastructure.  Dans un environnement Linux, tu utiliseras des outils tels que Git, GitLab, Spinnaker, Docker, Kubernetes, Helm ou encore Google Cloud Plateform, SQL, PostgreSQL, watchguard, HAproxy, Ansible‚Ä¶  Avantages : üè° 3 jours t√©l√©travail/semaine possibles üè∞ Bureaux coeur de ville üçï Tickets resto 8‚Ç¨ ‚öïÔ∏è Mutuelle prise en charge √† 60% üåû 9 √† 12 jours de RTT/an'

In [222]:
#Creation of a "skills" column from the skills mentioned in each job description

import numpy as np

skills1 = ["Python", "SQL", "AWS", "Spark", "Azure", " R ", "Tableau", "Java", "Excel", "Scala", "Hadoop", "Power BI", "Snowflake", "Kafka", "NoSQL", "DataBricks", "Redshift",
          "Git", "Oracle", "Airflow", "GCP", "Docker", "SQL Server", "SAS", "Kubernetes", "BI ", "Data Viz", "data visualisation", "Machine learning", "Machine Learning",
           "Deep learning", "Deep Learning" "Dashboard", "Postgresql", "API", "Big data", "Big Data", "ETL", "Agile", "CRM", "Devops", "DevOps", "d√©ploiement", "algorithmes"]

skills2 = [skill.lower() for skill in skills1]
skills = skills1 + skills2

dfW["global_job_desc"] = dfW["job_description"] + dfW["profile"] #Creation of a column "global_job_desc" grouping "job_description" and "profile"
column = "global_job_desc"

def found_skills(description):
    skills_found = []
    for skill in skills:
        if skill in description:
            skills_found.append(skill)
    return skills_found if skills_found else np.nan

dfW['global_job_desc'] = dfW['global_job_desc'].apply(lambda x: str(x))
dfW['profile'] = dfW['profile'].apply(lambda x: str(x))
dfW['skills'] = dfW[column].apply(found_skills)
dfW['skills'] = dfW['skills'].str.join(', ')

dfW

,job_title,job_type,job_location,company_size,job_company,industry,company_description,job_description,profile,global_job_desc,skills
0,Tools & Accounts Administrator,CDI,M√¢con‚Ä¶Voir plus2,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Au sein du d√©partement SI et en interaction av...,Profil recherch√© Dipl√¥m√©.e d‚Äôun bac+2 en lien...,Au sein du d√©partement SI et en interaction av...,"Azure, Git, CRM, DevOps, d√©ploiement, d√©ploiement"
1,Team Lead - Data Engineering & Analytics Engi...,CDI,"16 Rue du Mail, Paris, 75002",Entre 250 et 2000 salari√©s,Welcome to the Jungle,"M√©dia, Recrutement","Chez Welcome to the Jungle, nous travaillons p...",The Data team at Welcome to the Jungle: Part ...,"Profil recherch√© At Welcome to the Jungle, we...",The Data team at Welcome to the Jungle: Part ...,"Python, SQL, Excel, Snowflake, Airflow, scala"
2,DevSecOps Engineer (SI),CDI,M√¢con‚Ä¶Voir plus3,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Au sein du d√©partement DSI et en interaction a...,Profil recherch√© Tu as d√©j√† au moins 3 ans d‚Äô...,Au sein du d√©partement DSI et en interaction a...,"Python, SQL, Git, Docker, Kubernetes, DevOps, ..."
3,Data Analyst - Data Engineer (H/F),CDI,"21 Rue Berg√®re, Paris, 75009",Entre 50 et 250 salari√©s,Runview,Audit,"Runview, c‚Äôest le monde de l‚Äôaudit digitalis√©,...",Nous recherchons un(e) Data Analyst / Data Eng...,Profil recherch√© Vous √™tes issu(e) d‚Äôune form...,Nous recherchons un(e) Data Analyst / Data Eng...,"Power BI, BI"
4,[Luxe - Retail] Consultant Senior Data & Anal...,CDI,"18 Rue de Tilsitt, Paris, 75017",Entre 250 et 2000 salari√©s,Adone Conseil,"IT / Digital, Transformation",Si vous recherchez un cabinet √† taille humaine...,Nous recherchons un Consultant Senior Data & A...,Profil recherch√© ü¶∏ Votre profil : Vous √™tes ...,Nous recherchons un Consultant Senior Data & A...,"Power BI, BI"
...,...,...,...,...,...,...,...,...,...,...,...
954,Ing√©nieur Big Data - Retail - Bordeaux,CDI,"avenue de Pythagore, Bordeaux, 33700",> 2000 salari√©s,Sopra Steria,"IT / Digital, Organisation / Management","Sopra Steria, l'un des leaders europ√©ens de la...",Votre futur environnement de travail La Busin...,Profil recherch√© Votre profil De formation B...,Votre futur environnement de travail La Busin...,"Python, SQL, Spark, Java, Scala, Hadoop, Kafka..."
955,Data Wrangler,Stage ¬† (6 mois),"la defense, Puteaux",> 2000 salari√©s,Soci√©t√© G√©n√©rale,"Banque, FinTech / InsurTech, Finance","Chez Soci√©t√© G√©n√©rale, nous sommes convaincus ...","Le m√©tier Data Wrangler est, par nature, vari√©...",Profil recherch√© Vous √™tes √©tudiant(e) de form...,"Le m√©tier Data Wrangler est, par nature, vari√©...","API, api"
956,ALTERNANCE - Data Analyst (F/H),Alternance,"18, Rue Barb√®s, Montrouge, 92120",Entre 250 et 2000 salari√©s,Groupe Bayard,"Edition, M√©dia, Presse √©crite","Acteur majeur dans le secteur des m√©dias, Baya...",Au sein de l‚Äô√©quipe Data et Op√©rations CRM rat...,Profil recherch√© En formation sup√©rieure (bac...,Au sein de l‚Äô√©quipe Data et Op√©rations CRM rat...,"SQL, Tableau, CRM, python, git"
957,Alternance - Digital & Data Market Analyst - ...,Alternance,Serris,> 2000 salari√©s,Henkel,"Grande distribution, Cosm√©tique, E-commerce","En 1876, Fritz Henkel n‚Äôaurait jamais imagin√© ...","Chez Henkel, vous pouvez changer les r√®gles du...",nan,nan,NaN
958,ASSISTANT.E PRODUCT DATA MANAGER,CDD / Temporaire,"Paris 17, 75017",> 2000 salari√©s,Groupe Clarins,Cosm√©tique,Pr√™t √† insuffler de la passion √† votre carri√®r...,Le poste¬†: ¬† A la crois√©e du Marketing et du...,Profil recherch√© Description du profil : V...,Le poste¬†: ¬† A la crois√©e du Marketing et du...,"Excel, excel, git"

In [223]:
#Viz of skills columns for Welcome To The Jungle Dataset

dfW['profile'] = dfW['profile'].replace(['NaN','nan'],'')
dfW['job_description'].replace(['NaN','nan'],'')
dfW['global_job_desc'].isna().sum()

0

In [224]:
dfW['skills'].value_counts()

Excel                                                   11
tableau                                                 10
d√©ploiement, d√©ploiement                                 8
excel                                                    6
agile                                                    6
                                                        ..
Python, Airflow, GCP, ETL, scala                         1
Python, SQL, CRM, excel, git                             1
Excel, excel, api                                        1
AWS, Azure, Docker, algorithmes, python, algorithmes     1
SQL, Tableau, CRM, python, git                           1
Name: skills, Length: 660, dtype: int64

In [225]:
skills_count_W = dfW['skills'].str.split(', ', expand=True).stack().value_counts()
skills_count_W

Python           366
SQL              355
d√©ploiement      236
git              227
algorithmes      160
                ...
snowflake          1
bi                 1
Postgresql         1
hadoop             1
Deep learning      1
Length: 71, dtype: int64

In [226]:
#Creation of "skills" column for LinkedIn dataset

column = 'job_description'

dfL['skills'] = dfL[column].apply(found_skills)
dfL['skills'] = dfL['skills'].str.join(', ')

dfL

,job_title,job_link,job_company,job_location,job_description,Seniority_level,Employment_type,skills
0,Data Entry Operator (Remote),https://wf.linkedin.com/jobs/view/data-entry-o...,eStaffing Inc.,Wallis et Futuna,Job Tittle- Data Entry Operator (Remote) Job ...,Premier emploi,Temps plein,NaN
1,Data Entry Clerk - Remote,https://fr.linkedin.com/jobs/view/data-entry-c...,eStaffing Inc.,France,Job Tittle- Data Entry Celrk -Remote Job loca...,Premier emploi,Temps plein,NaN
2,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,E.Leclerc,Ivry-sur-Seine,Description L COMMERCE est compos√© de 100 col...,Premier emploi,Temps plein,"Python, SQL, Tableau, Java, NoSQL, BI , tablea..."
3,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,E.Leclerc,Toulouse,"Description Leader du drive en France, le gro...",Premier emploi,Temps plein,"Python, SQL, SAS, CRM, git"
4,Data Analyst,https://fr.linkedin.com/jobs/view/data-analyst...,Mirakl,Paris,Le secteur des marketplaces cro√Æt deux fois pl...,Premier emploi,Temps plein,"SQL, Tableau, Excel, BI , git, api"
...,...,...,...,...,...,...,...,...
926,Stage - bras droit co-fondateur - data & opera...,https://fr.linkedin.com/jobs/view/stage-bras-d...,Climb,Paris,L'entreprise : Notre mission : Permettre √†...,Non pertinent,Temps plein,"SQL, Tableau, excel, git, api"
927,Consultant Strat√©gie Cloud - H/F,https://fr.linkedin.com/jobs/view/consultant-s...,Thales,Lyon,QUI ETES-VOUS ? Dipl√¥m√© d‚Äôune grande √©cole...,Non pertinent,Temps plein,"Big Data, DevOps, git, api, agile"
928,Analytics Architect,https://fr.linkedin.com/jobs/view/analytics-ar...,IGT Solutions,Paris et p√©riph√©rie,Role - Data Scientist Skillsets - Technical s...,Manager,Temps plein,"Python, SQL, Azure, Java, Excel, BI , ETL, Agi..."
929,Accountant Fintech,https://fr.linkedin.com/jobs/view/accountant-f...,Mobilize Pay,"√éle-de-France, France","About us At MOBILIZE PAY, we‚Äôre on a missi...",Manager,Temps plein,NaN
930,Stage Business Analyst Parfums H/F,https://fr.linkedin.com/jobs/view/stage-busine...,Cartier,Paris,Cartier France recherche un(e) stagiaire : Bus...,Stagiaire / Alternant,Stage / Alternance,"Excel, CRM, tableau, git"

In [227]:
#Viz of skills column

skills_count_L = dfL['skills'].str.split(', ', expand=True).stack().value_counts()
skills_count_L

SQL            377
git            377
Python         334
Excel          272
d√©ploiement    210
              ...
power bi         1
etl              1
databricks       1
DataBricks       1
docker           1
Length: 68, dtype: int64

In [228]:
#Creation of "skills" column for Indeed dataset

column = 'job_description'

dfI['skills'] = dfI[column].apply(found_skills)
dfI['skills'] = dfI['skills'].str.join(', ')

dfI

<ipython-input-228-552f3b4492c7>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfI['skills'] = dfI[column].apply(found_skills)
<ipython-input-228-552f3b4492c7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfI['skills'] = dfI['skills'].str.join(', ')

,job_title,job_company,job_location,job_description,skills
0,Responsable Data engineer,arm√©e de l'Air et de l'Espace,33000 Bordeaux,Vous √™tes charg√©(e) :- De piloter et r√©aliser ...,NaN
1,DATA ENGINEER (H/F),EOSIS,13790 Rousset,Vous souhaitez rejoindre un groupe dynamique e...,"Python, SQL, Excel, Power BI, BI , API, ETL, t..."
2,Analyste d√©veloppeur - data scientist (H/F),EURO-INFORMATION DEVELOPPEMENTS,67000 Strasbourg,"Qui sommes nous Euro-Information, filiale tech...","Python, Machine Learning, d√©ploiement, algorit..."
3,Alternance - Data Steward H/F,Groupe GEMA,Montpellier (34),"L‚ÄôIA School, l‚ÄôEcole de l‚ÄôIntelligence Artific...","SQL, Excel, Power BI"
4,Consultant Senior Data Gouvernance (F/H),Novencia,Paris (75),Carnet de route Novencia accompagne ses client...,"Big Data, d√©ploiement, git, d√©ploiement"
...,...,...,...,...,...
1407,Data Engineer H/F,Dexton consulting,75002 Paris,Vous souhaitez int√©grer un groupe √† taille hum...,"Python, SQL, Spark, Azure, Tableau, Scala, Had..."
1408,INTERNSHIP OFFER - RESEARCH INTERNATIONAL PROJ...,SNCF,Saint-Denis (93),Vos missions The aim of this internship is to ...,"machine learning, machine learning"
1409,Analyste Quantitatif - Data Scientist (F/H),Ofi Invest Asset Management,Paris (75),A propos d'Ofi Invest : Ofi Invest est aujourd...,"Python, SQL, SQL Server, Machine Learning, alg..."
1410,DATA MANAGER RECHERCHE CLINIQUE (H/F) (Nouvell...,POLE DIRECTION,Bron (69),Quotit√© de temps % : 100 Poste jour / nuit : J...,NaN
1411,DATA SCIENTIST SCORE ET MODELISATION (F/H),BPCE Compagnie Europeenne de Garanties et Caut...,Paris (75),Description de l'entreprise La Compagnie Europ...,"Python, Git, SAS, git"

In [229]:
#Viz of skills column

skills_count_I = dfI['skills'].str.split(', ', expand=True).stack().value_counts()
skills_count_I

SQL                 422
Python              406
git                 348
machine learning    242
d√©ploiement         232
                   ...
nosql                 2
airflow               1
kafka                 1
 r                    1
oracle                1
Length: 69, dtype: int64

In [230]:
#Viz of NaN in skills column, for each dataset

dfI["skills"].isna().sum()/len(dfI["skills"])*100

6.860706860706861

In [231]:
dfW["skills"].isna().sum()/len(dfI["skills"])*100

18.91891891891892

In [232]:
dfL["skills"].isna().sum()/len(dfI["skills"])*100

3.8461538461538463

In [233]:
#Cleaning of location information, for each dataset

dfW["job_location"].value_counts()

Paris                                                                 27
Toute La France                                                       14
ZAC du Parc des Tulipes - Avenue du 21√®me Si√®cle  , Gonesse, 95500    12
117-119 Quai de Valmy, Paris, 75010                                   11
Toulouse, 31000                                                       11
                                                                      ..
128 rue de la boetie, Paris, 75008                                     1
6, Rue Beaubourg, Paris, 75004                                         1
Charenton-le-Pont, Charenton-Le-Pont                                   1
Mulhouse‚Ä¶Voir plus2                                                    1
Paris 17, 75017                                                        1
Name: job_location, Length: 546, dtype: int64

In [234]:
dfW["job_location"][1]

'16 Rue du Mail, Paris, 75002'

In [235]:
dfW["job_location"].apply(lambda x: x.split(", "))

0                          [M√¢con‚Ä¶Voir plus2]
1              [16 Rue du Mail, Paris, 75002]
2                          [M√¢con‚Ä¶Voir plus3]
3              [21 Rue Berg√®re, Paris, 75009]
4           [18 Rue de Tilsitt, Paris, 75017]
                        ...
954    [avenue de Pythagore, Bordeaux, 33700]
955                     [la defense, Puteaux]
956        [18, Rue Barb√®s, Montrouge, 92120]
957                                  [Serris]
958                         [Paris 17, 75017]
Name: job_location, Length: 959, dtype: object

In [236]:
#Import of a dataset containing the names of all the cities and regions of France

fr_cities_df = pd.read_excel('/content/drive/MyDrive/Jedha_Fullstack/DataMatch_Project/Data_Cleaning/Liste-Excel-des-villes-de-France.xlsx')

In [237]:
fr_cities_df.head()

,Population l√©gale des villes en vigueur au 1er janvier 2019 (INSEE),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,Nom de la commune,Population totale,D√©partement,R√©gion,D√©partements
2,Paris,2210875,75,Ile-de-France,Ain
3,Marseille,870018,13,Provence-Alpes-C√¥te d'Azur,Aisne
4,Lyon,523164,69,Auvergne-Rh√¥ne-Alpes,Allier

In [238]:
fr_cities_list = fr_cities_df.iloc[2:,0]
fr_regions_list = fr_cities_df.iloc[2:,3]
fr_dept_list = fr_cities_df.iloc[2:,4]
fr_list = pd.concat([fr_cities_list, fr_regions_list, fr_dept_list])
fr_list = fr_list.append(pd.Series(["La D√©fense", "France", "Sophia Antipolis", "Monaco", "T√©l√©travail"]), ignore_index=True)

<ipython-input-238-809b906c3247>:5: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  fr_list = fr_list.append(pd.Series(["La D√©fense", "France", "Sophia Antipolis", "Monaco", "T√©l√©travail"]), ignore_index=True)

In [239]:
#Creation of a function to clean up the name of the location of each job offer and application to each of the datasets

import re

def trouver_ville(texte):
    for ville in fr_list:
        if re.search(r'\b{}\b'.format(ville), texte, re.IGNORECASE):
            return ville
    return "Autre"

In [240]:
dfW["location"] = dfW["job_location"].apply(trouver_ville)
dfW["location"].value_counts()

Paris               415
Lyon                 31
Toulouse             29
Levallois-Perret     28
Autre                28
                   ...
Saclay                1
Gentilly              1
Marnaz                1
Prouvy                1
Serris                1
Name: location, Length: 120, dtype: int64

In [241]:
dfW["location"].isna().sum()

0

In [242]:
dfI["location"] = dfI["job_location"].apply(trouver_ville)

<ipython-input-242-f5923335c956>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfI["location"] = dfI["job_location"].apply(trouver_ville)

In [243]:
dfI["location"].value_counts()

Paris                   288
Lyon                     85
Autre                    26
La D√©fense               24
Lille                    23
                       ...
Clamart                   1
√âpernay                   1
Serris                    1
S√®vres                    1
Auvergne-Rh√¥ne-Alpes      1
Name: location, Length: 197, dtype: int64

In [244]:
dfI["location"].isna().sum()

0

In [245]:
dfL["location"] = dfL["job_location"].apply(lambda x : str(x)).apply(trouver_ville)

In [246]:
dfL["location"].value_counts()

Paris                   316
Lyon                     42
Boulogne-Billancourt     25
Bordeaux                 25
Toulouse                 20
                       ...
Blagnac                   1
Saint-Amand-les-Eaux      1
Nogent-sur-Seine          1
Mont√©vrain                1
Romans-sur-Is√®re          1
Name: location, Length: 154, dtype: int64

In [247]:
dfL["location"].isna().sum()

25

In [248]:
dfL.loc[dfL["location"].isna(),:]

,job_title,job_link,job_company,job_location,job_description,Seniority_level,Employment_type,skills,location
127,Data Analyste H/F (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Python, SQL, AWS, Tableau, Excel, Snowflake, d...",NaN
312,Data Analyst F/H - AIA Clermont-Ferrand (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,Oracle,NaN
335,Data scientist,https://fr.linkedin.com/jobs/view/data-scienti...,NaN,NaN,Entreprise ABYLSEN est un groupe de conseil e...,Premier emploi,Temps plein,"Python, SQL, Java, NoSQL, SAS, Machine Learnin...",NaN
423,Data scientist (H/F),https://fr.linkedin.com/jobs/view/data-scienti...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Python, SAS, Machine Learning, Big Data, algor...",NaN
431,Data analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Excel, Power BI, BI",NaN
450,Data Analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"algorithmes, git, algorithmes",NaN
482,Data Analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,NaN,NaN
489,Data scientist,https://fr.linkedin.com/jobs/view/data-scienti...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Python, SQL, Azure, R , Git, algorithmes, alg...",NaN
497,Data Scientist- (H/F),https://fr.linkedin.com/jobs/view/data-scienti...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Python, SQL, R , Power BI, NoSQL, Git, SAS, B...",NaN
608,Data analyst H/F,https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Description Du Poste L√âVAVI¬Æ -Expert en Recru...,Premier emploi,Temps plein,"Excel, ETL, git",NaN
633,Data analyst,https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Python, R , Tableau, Excel, Power BI",NaN
658,Data analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"SAS, CRM, python, machine learning, machine le...",NaN
659,DATA ANALYST (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Power BI, BI , tableau",NaN
697,"DATA ANALYST F/H - Syst√®me, r√©seaux, donn√©es (...",https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Python, Java, Big Data",NaN
755,Consultant d√©butant en data sciences (H/F),https://fr.linkedin.com/jobs/view/consultant-d...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Manager,Temps plein,"CRM, d√©ploiement, d√©ploiement",NaN
792,Data analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Python, SAS, Machine Learning, git",NaN
806,Data Analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,NaN,NaN
807,Ing√©nieur Data Scientist sp√©cialis√© dans l‚Äôexp...,https://fr.linkedin.com/jobs/view/ing%C3%A9nie...,NaN,NaN,Contexte : L‚Äô√©quipe projet Donn√©es Massives e...,Temps plein,NaN,"Python, SQL, Spark, R , Hadoop, NoSQL, Oracle...",NaN
820,Data Analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"git, agile",NaN
851,Data Analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"SQL, Excel, BI , Machine Learning, Big Data, t...",NaN
882,Data Analyst (H/F),https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"Excel, tableau",NaN
900,Assistant DATA SCIENTIST (H/F),https://fr.linkedin.com/jobs/view/assistant-da...,NaN,NaN,Cette offre d‚Äôemploi est fournie par P√¥le empl...,Premier emploi,Temps plein,"SQL, Tableau, Excel, Big Data",NaN
905,ALTERNANCE - Data Analyst F/H,https://fr.linkedin.com/jobs/view/alternance-d...,NaN,NaN,Entreprise A la recherche d'une alternance en...,Premier emploi,Stage / Alternance,"Power BI, BI , ETL",NaN
919,Analyste de donn√©es marketing / marketing data...,https://fr.linkedin.com/jobs/view/analyste-de-...,NaN,NaN,Cette offre d‚Äôemploi est fournie par ...,Manager,Temps plein,"Excel, Power BI, BI , CRM, git",NaN
923,Data Analyst H/F,https://fr.linkedin.com/jobs/view/data-analyst...,NaN,NaN,"Entreprise Akkodis, est un acteur mondial de ...",Premier emploi,Temps plein,"Python, SQL, excel, git",NaN

In [249]:
dfW = dfW.drop("job_location", axis=1)
dfW.head(5)

,job_title,job_type,company_size,job_company,industry,company_description,job_description,profile,global_job_desc,skills,location
0,Tools & Accounts Administrator,CDI,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Au sein du d√©partement SI et en interaction av...,Profil recherch√© Dipl√¥m√©.e d‚Äôun bac+2 en lien...,Au sein du d√©partement SI et en interaction av...,"Azure, Git, CRM, DevOps, d√©ploiement, d√©ploiement",M√¢con
1,Team Lead - Data Engineering & Analytics Engi...,CDI,Entre 250 et 2000 salari√©s,Welcome to the Jungle,"M√©dia, Recrutement","Chez Welcome to the Jungle, nous travaillons p...",The Data team at Welcome to the Jungle: Part ...,"Profil recherch√© At Welcome to the Jungle, we...",The Data team at Welcome to the Jungle: Part ...,"Python, SQL, Excel, Snowflake, Airflow, scala",Paris
2,DevSecOps Engineer (SI),CDI,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Au sein du d√©partement DSI et en interaction a...,Profil recherch√© Tu as d√©j√† au moins 3 ans d‚Äô...,Au sein du d√©partement DSI et en interaction a...,"Python, SQL, Git, Docker, Kubernetes, DevOps, ...",M√¢con
3,Data Analyst - Data Engineer (H/F),CDI,Entre 50 et 250 salari√©s,Runview,Audit,"Runview, c‚Äôest le monde de l‚Äôaudit digitalis√©,...",Nous recherchons un(e) Data Analyst / Data Eng...,Profil recherch√© Vous √™tes issu(e) d‚Äôune form...,Nous recherchons un(e) Data Analyst / Data Eng...,"Power BI, BI",Paris
4,[Luxe - Retail] Consultant Senior Data & Anal...,CDI,Entre 250 et 2000 salari√©s,Adone Conseil,"IT / Digital, Transformation",Si vous recherchez un cabinet √† taille humaine...,Nous recherchons un Consultant Senior Data & A...,Profil recherch√© ü¶∏ Votre profil : Vous √™tes ...,Nous recherchons un Consultant Senior Data & A...,"Power BI, BI",Paris

In [250]:
dfI = dfI.drop("job_location", axis=1)
dfI.head(5)

,job_title,job_company,job_description,skills,location
0,Responsable Data engineer,arm√©e de l'Air et de l'Espace,Vous √™tes charg√©(e) :- De piloter et r√©aliser ...,NaN,Bordeaux
1,DATA ENGINEER (H/F),EOSIS,Vous souhaitez rejoindre un groupe dynamique e...,"Python, SQL, Excel, Power BI, BI , API, ETL, t...",Rousset
2,Analyste d√©veloppeur - data scientist (H/F),EURO-INFORMATION DEVELOPPEMENTS,"Qui sommes nous Euro-Information, filiale tech...","Python, Machine Learning, d√©ploiement, algorit...",Strasbourg
3,Alternance - Data Steward H/F,Groupe GEMA,"L‚ÄôIA School, l‚ÄôEcole de l‚ÄôIntelligence Artific...","SQL, Excel, Power BI",Montpellier
4,Consultant Senior Data Gouvernance (F/H),Novencia,Carnet de route Novencia accompagne ses client...,"Big Data, d√©ploiement, git, d√©ploiement",Paris

In [251]:
dfL = dfL.drop("job_location", axis=1)
dfL.head(5)

,job_title,job_link,job_company,job_description,Seniority_level,Employment_type,skills,location
0,Data Entry Operator (Remote),https://wf.linkedin.com/jobs/view/data-entry-o...,eStaffing Inc.,Job Tittle- Data Entry Operator (Remote) Job ...,Premier emploi,Temps plein,NaN,Autre
1,Data Entry Clerk - Remote,https://fr.linkedin.com/jobs/view/data-entry-c...,eStaffing Inc.,Job Tittle- Data Entry Celrk -Remote Job loca...,Premier emploi,Temps plein,NaN,France
2,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,E.Leclerc,Description L COMMERCE est compos√© de 100 col...,Premier emploi,Temps plein,"Python, SQL, Tableau, Java, NoSQL, BI , tablea...",Ivry-sur-Seine
3,Data Analyst - H/F,https://fr.linkedin.com/jobs/view/data-analyst...,E.Leclerc,"Description Leader du drive en France, le gro...",Premier emploi,Temps plein,"Python, SQL, SAS, CRM, git",Toulouse
4,Data Analyst,https://fr.linkedin.com/jobs/view/data-analyst...,Mirakl,Le secteur des marketplaces cro√Æt deux fois pl...,Premier emploi,Temps plein,"SQL, Tableau, Excel, BI , git, api",Paris

In [252]:
dfW['platform'] = 'Welcome_to_the_Jungle'

In [253]:
dfI['platform'] = 'Indeed'

In [254]:
dfL['platform'] = 'LinkedIn'

In [255]:
dfGlobal = pd.concat([dfW, dfI, dfL], ignore_index=True)
dfGlobal

,job_title,job_type,company_size,job_company,industry,company_description,job_description,profile,global_job_desc,skills,location,platform,job_link,Seniority_level,Employment_type
0,Tools & Accounts Administrator,CDI,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Au sein du d√©partement SI et en interaction av...,Profil recherch√© Dipl√¥m√©.e d‚Äôun bac+2 en lien...,Au sein du d√©partement SI et en interaction av...,"Azure, Git, CRM, DevOps, d√©ploiement, d√©ploiement",M√¢con,Welcome_to_the_Jungle,NaN,NaN,NaN
1,Team Lead - Data Engineering & Analytics Engi...,CDI,Entre 250 et 2000 salari√©s,Welcome to the Jungle,"M√©dia, Recrutement","Chez Welcome to the Jungle, nous travaillons p...",The Data team at Welcome to the Jungle: Part ...,"Profil recherch√© At Welcome to the Jungle, we...",The Data team at Welcome to the Jungle: Part ...,"Python, SQL, Excel, Snowflake, Airflow, scala",Paris,Welcome_to_the_Jungle,NaN,NaN,NaN
2,DevSecOps Engineer (SI),CDI,Entre 50 et 250 salari√©s,Matawan (ex Ubitransport),"Logiciels, Mobilit√©","üöç Acteur des mobilit√©s partag√©es, Matawan prop...",Au sein du d√©partement DSI et en interaction a...,Profil recherch√© Tu as d√©j√† au moins 3 ans d‚Äô...,Au sein du d√©partement DSI et en interaction a...,"Python, SQL, Git, Docker, Kubernetes, DevOps, ...",M√¢con,Welcome_to_the_Jungle,NaN,NaN,NaN
3,Data Analyst - Data Engineer (H/F),CDI,Entre 50 et 250 salari√©s,Runview,Audit,"Runview, c‚Äôest le monde de l‚Äôaudit digitalis√©,...",Nous recherchons un(e) Data Analyst / Data Eng...,Profil recherch√© Vous √™tes issu(e) d‚Äôune form...,Nous recherchons un(e) Data Analyst / Data Eng...,"Power BI, BI",Paris,Welcome_to_the_Jungle,NaN,NaN,NaN
4,[Luxe - Retail] Consultant Senior Data & Anal...,CDI,Entre 250 et 2000 salari√©s,Adone Conseil,"IT / Digital, Transformation",Si vous recherchez un cabinet √† taille humaine...,Nous recherchons un Consultant Senior Data & A...,Profil recherch√© ü¶∏ Votre profil : Vous √™tes ...,Nous recherchons un Consultant Senior Data & A...,"Power BI, BI",Paris,Welcome_to_the_Jungle,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2847,Stage - bras droit co-fondateur - data & opera...,NaN,NaN,Climb,NaN,NaN,L'entreprise : Notre mission : Permettre √†...,NaN,NaN,"SQL, Tableau, excel, git, api",Paris,LinkedIn,https://fr.linkedin.com/jobs/view/stage-bras-d...,Non pertinent,Temps plein
2848,Consultant Strat√©gie Cloud - H/F,NaN,NaN,Thales,NaN,NaN,QUI ETES-VOUS ? Dipl√¥m√© d‚Äôune grande √©cole...,NaN,NaN,"Big Data, DevOps, git, api, agile",Lyon,LinkedIn,https://fr.linkedin.com/jobs/view/consultant-s...,Non pertinent,Temps plein
2849,Analytics Architect,NaN,NaN,IGT Solutions,NaN,NaN,Role - Data Scientist Skillsets - Technical s...,NaN,NaN,"Python, SQL, Azure, Java, Excel, BI , ETL, Agi...",Paris,LinkedIn,https://fr.linkedin.com/jobs/view/analytics-ar...,Manager,Temps plein
2850,Accountant Fintech,NaN,NaN,Mobilize Pay,NaN,NaN,"About us At MOBILIZE PAY, we‚Äôre on a missi...",NaN,NaN,NaN,√éle-de-France,LinkedIn,https://fr.linkedin.com/jobs/view/accountant-f...,Manager,Temps plein
2851,Stage Business Analyst Parfums H/F,NaN,NaN,Cartier,NaN,NaN,Cartier France recherche un(e) stagiaire : Bus...,NaN,NaN,"Excel, CRM, tableau, git",Paris,LinkedIn,https://fr.linkedin.com/jobs/view/stage-busine...,Stagiaire / Alternant,Stage / Alternance

In [256]:
#Creation of a "job_class" column to categorize job titles

job_mapping = {
    'data scientist': ['scien'],
    'data engineer': ['engin', 'ing√©nieur'],
    'consultant data': ['consultant'],
    'master data': ['master'],
    'product owner': ['product'],
    'd√©veloppeur': ['d√©veloppeur', 'developpeur', 'ops'],
    'business analyst': ['business'],
    'data analyst': ['analys'],
    'responsable data': ['responsable', 'data'],
    'technicien data': ['technicien', 'datacenter', 'ing√©nierie', 'donn√©e'],
    'comptable': ['comptable'],
    'responsable exploitation': ['responsable', 'exploitation'],
    'responsable environnement': ['environnement'],
    'charg√© de projet': ['projet', 'chef', 'mission', 'charg√© de campagne'],
    'data manager': ['manager'],
    'big data': ['big data'],
    'charg√© de communication': ['communication'],
    'charg√© de marketing': ['marketing', 'webmarketing'],
    'responsable commercial': ['commercial', 'commerce'],
    'expert CRM': ['expert', 'CRM', 'responsable', 'crm'],
    'expert SAP': ['expert', 'SAP'],
    'data designer': ['designer'],
    'statisticien': ['statisticien', 'statistiques'],
    'expert bi': ['expert', 'bi'],
    'administrateur bases de donn√©es': ['administrateur', 'donn√©es'],
    'tech lead': ['tech', 'lead'],
    'charg√© de reporting': ['reporting'],
    'auditeur': ['auditeur'],
    'expert cloud et r√©seaux': ['cloud', 'r√©seau', 'administrateur', 'r√©seaux'],
    'expert cybers√©curit√©': ['s√©curit√©'],
    'data architect': ['architect'],
    'data steward': ['steward'],
    'autres': []
}

def map_job_class(job_title):
    job_title_lower = job_title.lower()
    for category, keywords in job_mapping.items():
        for keyword in keywords:
            if keyword in job_title_lower:
                return category
    return 'autres'

dfGlobal['job_class'] = dfGlobal['job_title'].apply(map_job_class)

In [257]:
dfGlobal['job_class'].value_counts()

data analyst                       754
data engineer                      531
data scientist                     484
responsable data                   473
consultant data                    220
business analyst                    89
autres                              69
product owner                       68
d√©veloppeur                         47
technicien data                     32
data manager                        23
master data                         18
charg√© de projet                    14
statisticien                         5
charg√© de marketing                  5
expert CRM                           4
tech lead                            4
administrateur bases de donn√©es      2
expert bi                            2
charg√© de communication              2
data architect                       2
auditeur                             2
charg√© de reporting                  1
expert cybers√©curit√©                 1
Name: job_class, dtype: int64

In [258]:
dfGlobal.to_csv('dfGlobal.csv', index=False)